Metrics/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - 'shop_parsers/*/*.rb'

Style/MutableConstant:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/spec_helper.rb'

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
