AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'spec/spec_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/environments/*'

Style/Documentation:
  Enabled: false
  Exclude:
    - 'app/serializers/*.rb'
    - 'app/workers/*.rb'
    - 'app/controllers/*.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 17

Metrics/MethodLength:
  Max: 12

Naming/PredicateName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
