Style/Documentation:
  Enabled: false
  # Exclude:
  #   - 'shop_parsers/*/*.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Metrics/AbcSize:
#   Max: 20
#   Exclude:
#     - 'app/models/user.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/*.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/environments/*'

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'spec/spec_helper.rb'
