language: ruby

sudo: false

cache: bundler

addons:
  postgresql: 9.6

before_script:
  - 'cp config/database.yml.travis config/database.yml'
  - 'RAILS_ENV=test bundle exec rake db:create --trace'

script:
  - bundle exec rspec

notifications:
  email: false
