# silpo:
#   name: Сільпо
#   url: https://silpo.ua
#   discount_types:
#     price_of_the_week:
#       name: Ціна тижня
#       url: https://silpo.ua/offers/cina-tizhnya
#       js: true
#       period:
#         starts_at: 18 Jan 2018
#         duration_in_days: 7
#       discounts_xpath: "//ul[contains(@class, 'product-list product-list__per-row-3')]/li[contains(@class,
#         'normal')]/a[contains(@class, 'product-list__item normal size-normal')]"
#       discount:
#         name_xpath: "//div[contains(@class, 'product-list__item-description')]"
#         image_xpath: "//div[contains(@class, 'product-list__item-image')]/img"
#         new_price_divided: true
#         new_price_integer_xpath: "//div[contains(@class, 'product-price__integer')]"
#         new_price_fraction_xpath: "//div[contains(@class, 'product-price__fraction')]"
#         old_price_xpath: "//div[contains(@class, 'product-price__other')]/div[contains(@class, 'product-price__old')]"
#       pagination:
#         parameter: offset
#         starts_at: 0
#         step: 6
#         pages_count_xpath: "//a[contains(@class, 'pagination-link')][3]"
#     own_import_discounts:
#       name: Акції Власного імпорту
#       url: https://silpo.ua/offers/akciyi-vlasnogo-importu
#       js: true
#       period:
#         starts_at: 18 Jan 2018
#         duration_in_days: 7
#       discounts_xpath: "//ul[contains(@class, 'product-list product-list__per-row-3')]/li[contains(@class,
#         'normal')]/a[contains(@class, 'product-list__item normal size-normal')]"
#       discount:
#         name_xpath: "//div[contains(@class, 'product-list__item-description')]"
#         image_xpath: "//div[contains(@class, 'product-list__item-image')]/img"
#         new_price_divided: true
#         new_price_integer_xpath: "//div[contains(@class, 'product-price__integer')]"
#         new_price_fraction_xpath: "//div[contains(@class, 'product-price__fraction')]"
#         old_price_xpath: "//div[contains(@class, 'product-price__other')]/div[contains(@class, 'product-price__old')]"
#       pagination:
#         parameter: offset
#         starts_at: 0
#         step: 6
#         pages_count_xpath: "//a[contains(@class, 'pagination-link')][3]"

atb:
  name: АТБ
  url: https://silpo.ua
  discount_types:
    economy:
      name: Економія
      url: http://www.atbmarket.com/hot/akcii/economy/
      period:
        starts_at: 31 Jan 2018
        duration_in_days: 7
      discounts_xpath: "//ul[contains(@class, 'promo_list')]/li"
      discount:
        name_xpath: "//span[contains(@class, 'promo_info_text')]"
        image_xpath: "//a[contains(@class, 'promo_image_link')]/img"
        image_relative_url: true
        image_base_url: http://www.atbmarket.com/
        new_price_divided: true
        new_price_integer_xpath: "//div[contains(@class, 'promo_price')]/text()"
        new_price_fraction_xpath: "//div[contains(@class, 'promo_price')]/span[1]"
        old_price_xpath: "//span[contains(@class, 'promo_old_price')]"
